    SUBROUTINE CONFIG(NY,EPSILON,SGM,PMLY,DY,W_CO,W_PT,JB,J1,J2,SIGMA1,SIGMA2,EPS_INF,TA_LAYER)
	
	IMPLICIT NONE
	
	INTEGER NY, PMLY, FLAG_FCR
	REAL*8 EPSILON(NY+1), SGM(NY+1)
	INTEGER J, CENTER_Y, JB, J1, J2
	REAL*8 DY
	REAL*8 W_CO, W_PT
	REAL*8 SIGMA1, SIGMA2, EPS_INF
	REAL*8 TA_LAYER

	CENTER_Y = NY/2
	TA_LAYER = 0.0D0	
	JB = 14-CEILING(5.0D-9/DY)
		
	WRITE(*,*) 'BOUNDARY BETWEEN FILMS', JB

!	COBALT
	DO J = JB, JB-CEILING(W_CO/DY), -1

		EPSILON(J) = EPS_INF
		SGM(J) = SIGMA1
                        
    END DO

	J1 = J+1 !outer boundary
	WRITE(*,*) 'OUTER BOUNDARY FILM 1', J1

!	PERMALLOY
	DO J = JB+1, JB+CEILING(W_PT/DY)

		EPSILON(J) = EPS_INF
		SGM(J) = SIGMA2
                        
    END DO
    
    J2 = J-1 !outer boundary
    WRITE(*,*) 'OUTER BOUNDARY FILM 2', J2

! TANTALUM LAYERS

	DO J = J1-CEILING(TA_LAYER/DY), J1-1

		EPSILON(J) = EPS_INF
		SGM(J) = 1.0D0/131.0D-9
                        
    END DO
	
	DO J = J2+1, J2+CEILING(TA_LAYER/DY)

		EPSILON(J) = EPS_INF
		SGM(J) = 1.0D0/131.0D-9
                        
    END DO

	WRITE(*,*) 'THE FIRST Ta FILM LIMITS', J1-CEILING(TA_LAYER/DY), J1-1
	WRITE(*,*) 'THE SECOND Ta FILM LIMITS', J2+1, J2+CEILING(TA_LAYER/DY)
	WRITE(*,*) 'THE SOURCE POSITION ', J1-CEILING(TA_LAYER/DY)-1

	OPEN (UNIT=34,FILE='SGM.OUT',STATUS='UNKNOWN')
        DO J=1, NY+1
                WRITE(34,"(1X, E18.8E3)")  SGM(J)

        ENDDO
        CLOSE(34)

	WRITE(*,*) 'CONFIG OK!'
	
	END
